### ISSUE TITLE
Adding DECam g,r,i,z as a PhotometricSystem

### ISSUE THREAD

**Issue by psferguson** [gaia-dpci/GaiaXPy#20]
Hello,
I was wondering if it would be possible to add the DECam g,r,i,z bandpasses as a PhotometricSystem in GaiaXPy?
I think the filter transformation information is available here: https://noirlab.edu/science/programs/ctio/filters/Dark-Energy-Camera

Alternatively, if there was documentation for creating the GaiaXPy filter config files that would also work.

Thanks so much,
-Peter Ferguson

**Comment by fdeangeli** [comment]
Hi Peter,

The DECam system has been added in the 1.1.4 release of GaiaXPy.

The code generating the filter bases has been used and validated extensively with other photometric systems, but no specific validation for the DECam synthetic photometry has been done. There are known systematics in the BP/RP spectra that will affect the synthetic photometry, particularly for bands covering wavelength ranges bluer than 400 nm and for faint sources. These are well detailed in the DR3 papers (Gaia Collaboration, Montegriffo et al. 2022, Montegriffo et al. 2022 and De Angeli et al. 2022).

Kind regards,
Francesca De Angeli

**Comment by dnidever** [comment]
Hi Francesca,

Would it also be possible to add the DECam u-band and VR-filters to gaiaxpy.  They are available at https://noirlab.edu/science/programs/ctio/filters/Dark-Energy-Camera
as well.

Thanks,
David Nidever

**Comment by fdeangeli** [comment]
Hi David,

sorry for not replying earlier, but you added your request as a comment to a closed issue. It would have been better to create a new issue. Much more visible :)
Actually, could I please ask you to do so, i.e. create a new issue just copying and pasting the text above?

I will add the following comment to the newly generated issue when available, but just to speed things up, I had a look at the DECam filters page. The system we offer in GaiaXPy is the first one from that page (DES standard bandpasses). The u and VR are only available from the second set, which also includes different definitions for grizY. Unfortunately, the two systems are not clearly labelled and we are concerned that if we now add u and VR, it will be unclear for users which of the grizY filters we have used. You should also be aware that the Gaia BP spectra do not cover the full range of the u band. 

Thanks,
Francesca
