### ISSUE TITLE
[#RVO-137-49936]: Gaia Datalink XP_SAMPLED Returned Wavelength Not Granular

### ISSUE THREAD

**Issue by JosephKarpinski** [gaia-dpci/GaiaXPy#27]
Hi,

Not sure if GaiaXPy

The helpdesk sent me here.

Here's the submitted issue

<img width="935" alt="Screen Shot 2022-07-03 at 2 25 25 PM" src="https://user-images.githubusercontent.com/37123616/178068680-c6c580ee-4698-42f5-8058-70c1652195de.PNG">

Here's their reply:

XP spectra can be resampled to your liking using the GaiaXPy package: https://www.cosmos.esa.int/web/gaia/gaiaxpy
Note, however, that the BP/RP instruments are spectra-photometers with very low resolution (of order a few dozen at most, depending on wavelength).

XP_SAMPLED is not granular enough to identify spectral lines
RVS is.

Is there a way of passing the source_id to GaiaXpy to generate more granular flux/wavelenth values for a select star?

<img width="787" alt="Screen Shot 2022-07-05 at 11 29 51 PM" src="https://user-images.githubusercontent.com/37123616/178069944-6ae57657-dbaa-482a-86ca-bab7a15f2969.PNG">

<img width="673" alt="Screen Shot 2022-07-07 at 11 38 13 PM" src="https://user-images.githubusercontent.com/37123616/178069968-8bc05c1c-90f8-4a73-b8cc-545d3e43f062.PNG">

**Comment by fdeangeli** [comment]
The reply provided by the Gaia Helpdesk is correct. The BP/RP spectra are low-resolution spectra (the resolution covers the range 100 to 30 for BP and 100 to 70 for RP in $\lambda / \Delta \lambda$). Even with GaiaXPy you will not be able to increase the resolution of the spectra.
 
What GaiaXPy allows to generate is a BP/RP spectrum with a custom sampling, i.e. a finer or corser sampling. The tutorial available at
https://gaia-dpci.github.io/GaiaXPy-website/tutorials/Calibrator%20tutorial.html
shows how to generate a absolute spectra for a list of source ids (via a query to the archive) and how to customise the sampling.
