### ISSUE TITLE
OSError: [Errno 5] Input/output error: 'XP_CONTINUOUS_COMBINED_Gaia_DR3.xml'

### ISSUE THREAD

**Issue by aomkr** [gaia-dpci/GaiaXPy#32]
I am trying to do the synthetic photometry for the BP/RP spectra using GaiaXPy. I have downloaded the source_ids (171960) for which I need to get the spectra file and do the photometry. Because of the download threshold, I am dividing my chunks into 35 and did the download as mentioned in the Datalink example and been written into a new .xml file.
But when I try to give this file as an input to the synthetic photometry module, I am getting the error mentioned in the Subject here and could not do it. 

![code](https://user-images.githubusercontent.com/114741415/193260842-cd94d81a-b235-4aba-92f6-86aea2462466.png)
![error](https://user-images.githubusercontent.com/114741415/193260850-8e18ecfa-e1df-4d66-a518-942aebd3b409.png)

PS: I have tried the same with just 2 chunks of data (10000 spectra) with the same code and everything worked fine!! I crossmatched the input and output sourceids and got all 10000 matches. 
But for the entire data, when I tried to crossmatch the output sources I got only 5000 matches. So, I am confused. 
I wrote to the Gaia Helpdesk and they redirected me here!

It would be of great help if you can figure out where I am going wrong!!

Thanks in advance!

**Comment by druzm** [comment]
Hi @aomkr,

I am not entirely sure why you were redirected here as the problem you encountered seems to have to do with astroquery and not with GaiaXPy. Nevertheless, I tried running your code and found no errors. You can try providing the versions of the libraries you used to see whether it can be replicated.

If you're interested in extracting this data to pass it as input to GaiaXPy, extracting it this way is not required. The different functions in the package can receive a list of source IDs and query the Archive internally, like this:
```
from gaiaxpy import calibrate
import pandas as pd

def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

f = 'your_source_id_file.csv'
df = pd.read_csv(f)

dl_threshold = 5000
ids = df['source_id']
ids_chunks = list(chunks(ids, dl_threshold))

for chunk in ids_chunks:
    spectra_df, sampling = calibrate(list(chunk.values))
    # Do something with spectra_df
```

Cheers.

**Comment by aomkr** [comment]
Hi @druzm 
Thank you for looking into the issue. When you said, my codes worked for you I figured, the problem might be caused because of insufficient memory (RAM) to process my datafiles. So, I tried running my code in a cluster/server and now I got the output file without any error.

Thanks for helping!
