### ISSUE TITLE
Matplotlib 3.6 compatibility

### ISSUE THREAD

**Issue by pcasenove** [gaia-dpci/GaiaXPy#42]
Hello,
We are evaluating the inclusion on gaiaXpy library in the Euclid ground segment software stack.
In the requirements.txt file, there is a constraint on matplotlib that must be lower than 3.5.3. Is there any plan to add 3.6 support any time soon?

THanks!

**Comment by druzm** [comment]
Hi @pcasenove,

Technically there's no plan to add support for it, but I totally understand that having this constraint is not ideal, especially if you need to install GaiaXPy along with other packages. So, I can work on a new version of GaiaXPy in which this constraint is no longer present.

I'll let you know when it is ready.

**Comment by druzm** [comment]
Hello again,

I've just released GaiaXPy 1.2.3 which removes the constraint. If you encounter any issues with this version, just let me know through another issue.
