### ISSUE TITLE
Path error while downloading Gaiaxp spectra data

### ISSUE THREAD

**Issue by aomkr** [gaia-dpci/GaiaXPy#44]
Hello,

I am using the same code #32 to download. While trying to download the Gaia XP spectra in large volumes, I am getting the following errors. And I am not able to download after the first chunk. The code stops.

![image](https://user-images.githubusercontent.com/114741415/205919765-5b6d5863-77d2-4e1b-bc4d-d7154eaa3d46.png)

![image](https://user-images.githubusercontent.com/114741415/205919988-b6bf9417-63d1-44b2-8322-0c4da5a27453.png)

PS: It was working for a while even though it was showing the same path error before. And now I am getting these errors.
![image](https://user-images.githubusercontent.com/114741415/205919862-64bce643-8704-4e38-a984-87e245698840.png)

It would be great if you could point out where I am going wrrong.

**Comment by druzm** [comment]
Sorry for not replying to you sooner. I was postponing the resolution of this issue as it is not related to GaiaXPy but to astroquery, just like I mentioned in the previous issue you raised (although I understand you were redirected here).

You can contact the author of the Gaia astroquery module. His email is mentioned on the module itself [here](https://github.com/astropy/astroquery/blob/main/astroquery/gaia/core.py).
