### ISSUE TITLE
Request to add SITELLE filters

### ISSUE THREAD

**Issue by damienbeaulieu** [gaia-dpci/GaiaXPy#58]
Hi! 

I am part of the SIGNALS team, a large observing program (55+ nights) designed to study HII regions in nearby galaxies [1].  We are using SITELLE [2], installed at the CFHT since 2015 and we are looking for a new flux calibration method using Gaia DR3! We were wondering if you could add our seven filters (see figure) to your list of photometric systems? 

I have the transmission photonic curves [3] in .csv format ready, how would like to receive them? And we would like to use the VEGA magnitude system.
 
 
[1] Rousseau-Nepton et al. (2019), "SIGNALS: I. Survey description", https://ui.adsabs.harvard.edu/abs/2019MNRAS.489.5530R/abstract \
[2] Drissen et al. (2019), "SITELLE: an Imaging Fourier Transform Spectrometer for the Canada-France-Hawaii Telescope", https://ui.adsabs.harvard.edu/abs/2019MNRAS.485.3930D/abstract \
[3] Martin et al. (2021), "Data reduction and calibration accuracy of the imaging Fourier transform spectrometer SITELLE", https://ui.adsabs.harvard.edu/abs/2021MNRAS.505.5514M/abstract
 
Best,\
Damien

<img width="701" alt="SITELLEandGAIA" src="https://github.com/gaia-dpci/GaiaXPy/assets/45601255/391d891d-3e1f-4142-ab0f-56db76b96baf">

**Comment by fdeangeli** [comment]
Sorry for the delay replying to your request. Please provide the csv files by attaching them to this issue. You can simply drag and drop files in the editor window.

Cheers,
Francesca

**Comment by damienbeaulieu** [comment]
Here they are, thanks!

Damien

[SITELLE_C1_TransCurve.csv](https://github.com/gaia-dpci/GaiaXPy/files/11819745/SITELLE_C1_TransCurve.csv)
[SITELLE_C2_TransCurve.csv](https://github.com/gaia-dpci/GaiaXPy/files/11819748/SITELLE_C2_TransCurve.csv)
[SITELLE_C3_TransCurve.csv](https://github.com/gaia-dpci/GaiaXPy/files/11819750/SITELLE_C3_TransCurve.csv)
[SITELLE_C4_TransCurve.csv](https://github.com/gaia-dpci/GaiaXPy/files/11819751/SITELLE_C4_TransCurve.csv)
[SITELLE_SN1_TransCurve.csv](https://github.com/gaia-dpci/GaiaXPy/files/11819752/SITELLE_SN1_TransCurve.csv)
[SITELLE_SN2_TransCurve.csv](https://github.com/gaia-dpci/GaiaXPy/files/11819753/SITELLE_SN2_TransCurve.csv)
[SITELLE_SN3_TransCurve.csv](https://github.com/gaia-dpci/GaiaXPy/files/11819754/SITELLE_SN3_TransCurve.csv)

**Comment by fdeangeli** [comment]
Hi Damien, 
Please find attached the configuration file for your filters. To ensure the new file is loaded in GaiaXPy you will need to use the load_additional_systems function and point it to the folder where the new file is located. By calling get_available_systems afterwards you can confirm that the new system has been loaded:

```
PhotometricSystem = load_additional_systems('PATH_TO_FOLDER_WITH_NEW_FILTER_FILE')
print(PhotometricSystem.get_available_systems())
```

Do not hesitate contacting us if you encounter issues.
Kind regards
[Sitelle.gaiaXPy_dr3_v1.xml.gz](https://github.com/gaia-dpci/GaiaXPy/files/13649576/Sitelle.gaiaXPy_dr3_v1.xml.gz)

**Comment by fdeangeli** [comment]
Requested filters provided.
