### ISSUE TITLE
Requesting for the right structure in XML format regarding additional photometric systems for GaiaXPy 

### ISSUE THREAD

**Issue by Maryam345** [gaia-dpci/GaiaXPy#68]
Hello, 

As part of our research, we are interested in using our own photometric system by the Gaiaxpy tool. 
However, we could not make a readable XML format structure containing our data (wavelength, transmission). Then we were wondering if it is even possible to create our own photometric system locally without requesting you to convert it.   

I would appreciate it if you could guide us in this matter.
As an example, we are trying to convert the CSV file (kodak_103a_D) into XML format in order to use the intended function as a test. [kodak_103a_D.csv]

(https://github.com/gaia-dpci/GaiaXPy/files/13415430/kodak_103a_D.csv)

We're looking forward to hearing you promptly.

Best,
Maryam Raouph

**Comment by fdeangeli** [comment]
Dear Maryam, 

Sorry for the slow reply. Could you please confirm that you approached first the Gaia helpdesk and were redirected here?

The configuration files required to generate synthetic photometry do not merely contain the filter definition (e.g. arrays of wavelength and filter transmissivity curve).

We do not plan to add code to generate the configuration files for new filters as part of GaiaXPy, but we offer the service of generating these additional configuration files that can then be loaded by the user. Instructions are available at this page (FAQ):
https://gaiaxpy.readthedocs.io/en/latest/faqs.html#how-can-i-request-a-photometric-system-to-be-added

Kind regards,
Francesca De Angeli

**Comment by Maryam345** [comment]
Dear Dr. De Angeli,

Many thanks for the response.

No. I posted my request on GitHub on November 20 and, given the time-sensitive nature of my project situation, after three days of waiting, got my first contact with the Gaia help desk. They guided me to use the 'Report an issue/Suggest a feature' on the website, which I've already done. 
The latest communication with the Gaia help desk was on December 11, three weeks after my initial GitHub submission.

Respects,
Maryam Raouph

**Comment by Maryam345** [comment]
Dear Dr. De Angeli,

Many thanks for the response.

No. I posted my request on GitHub on November 20 and, given the time-sensitive nature of my project situation, after three days of waiting, got my first contact with the Gaia help desk. They guided me to use the 'Report an issue/Suggest a feature' on the website, which I've already done.
The latest communication with the Gaia help desk was on December 11, three weeks after my initial GitHub submission.

Respects,
Maryam Raouph

**Comment by fdeangeli** [comment]
I am not sure why this issue was reopened with no further message. I think you have now obtained the configuration files needed for your project via other channels than this issue. Can this be colsed?
