### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by dvallsgabaud** [gaia-dpci/GaiaXPy#76]
Hello,

I am trying to use the tutorial code in [https://gaia-dpci.github.io/GaiaXPy-website/tutorials/Linefinder%20tutorial.html ]
but it fails because find_fast or find_lines are missing. 
In fact, the are not in the API [https://gaiaxpy.readthedocs.io/en/latest/gaiaxpy.html])

The simple line
from gaiaxp import find_fast
yields
ImportError: cannot import name 'find_fast' from 'gaiaxpy'

I am using the latest release, v2.1.0. Have these features be removed from the release?
Thanks for your help.

**Comment by druzm** [comment]
Hello @dvallsgabaud,

Thank you for reporting this issue. There's a note I should have included in the tutorial to indicate that the line finder utility isn't part of a release yet and needs to be obtained from a specific branch.

If you wish to use this functionality, you'll need to clone the [line-finder](https://github.com/gaia-dpci/GaiaXPy/tree/line-finder) branch, and install the code from source.

Let me know if you need further instructions to make it work. I'll get sure to include the missing note in the tutorial.

Best,
Daniela

**Comment by dvallsgabaud** [comment]
Thank you Daniela, it now works fine, although there is a small bug in the y labels of the plots: they appear not to use LaTeX and produce labels such as W nm^-1 m^-2.
Thanks again for a very useful tool.
All best,

  David

**Comment by druzm** [comment]
Hi David,

It's good to know it works now. The plotter was developed as a simple tool for visualization rather than a tool to generate 'final' plots, but I'll take your suggestion of using LaTeX in the labels as it would be a nice improvement.

Cheers,
Daniela
